// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5JI1pdolz7QW3_igQYh4X4VsAp71mJc',
    appId: '1:658385923250:web:c23d829ba931aca2b56dab',
    messagingSenderId: '658385923250',
    projectId: 'smart-irrigation-5ac56',
    authDomain: 'smart-irrigation-5ac56.firebaseapp.com',
    storageBucket: 'smart-irrigation-5ac56.appspot.com',
    measurementId: 'G-HXRSF06DP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLP6T-UadcS4-axwjK4ZKi1PhhiqLLPc',
    appId: '1:658385923250:android:48fa8abd43ec70d4b56dab',
    messagingSenderId: '658385923250',
    projectId: 'smart-irrigation-5ac56',
    storageBucket: 'smart-irrigation-5ac56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGG-fjZGnOh4fJBCBVV5yHDS8opRXVTk',
    appId: '1:658385923250:ios:74b60a5ad00d7e1ab56dab',
    messagingSenderId: '658385923250',
    projectId: 'smart-irrigation-5ac56',
    storageBucket: 'smart-irrigation-5ac56.appspot.com',
    iosBundleId: 'com.example.smartirrigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb5JI1pdolz7QW3_igQYh4X4VsAp71mJc',
    appId: '1:658385923250:web:b27c13560ab5e26bb56dab',
    messagingSenderId: '658385923250',
    projectId: 'smart-irrigation-5ac56',
    authDomain: 'smart-irrigation-5ac56.firebaseapp.com',
    storageBucket: 'smart-irrigation-5ac56.appspot.com',
    measurementId: 'G-VGF6TVJYB3',
  );
}
